# Generated by Django 4.2.5 on 2023-10-04 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineshop', '0005_rename_product_ad_createad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CreateAd',
        ),
    ]
