# Generated by Django 4.2.3 on 2023-10-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0007_remove_item_is_sold_item_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="item_images/"),
        ),
    ]
