# Generated by Django 4.2.3 on 2023-11-04 12:37

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0014_item_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_county",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_street_address1",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_street_address2",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_town_or_city",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
