# Generated by Django 4.2.7 on 2023-11-29 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0015_userprofile_default_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receiver",
            new_name="recipient",
        ),
    ]
