# Generated by Django 4.2.7 on 2023-11-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0016_rename_receiver_message_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onlineshop.message",
            ),
        ),
    ]
