# Generated by Django 5.0 on 2023-12-19 12:07

import onlineshop.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0017_message_parent_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to=onlineshop.models.upload_to),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
