# Generated by Django 5.0.1 on 2024-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0019_remove_item_location_remove_item_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
