# Generated by Django 5.0.1 on 2024-01-18 14:15

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0020_item_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="default_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
