# Generated by Django 5.0.1 on 2024-01-18 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlineshop", "0022_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
