# Generated by Django 5.0.3 on 2024-04-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0023_delete_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="sku",
        ),
    ]
